// <auto-generated />
using System;
using AutomationEdariSamyaran.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomationEdariSamyaran.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250928134825_add-user")]
    partial class adduser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSetting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "BackupPath",
                            Value = "C:\\Backup"
                        },
                        new
                        {
                            Id = 2,
                            Key = "ApplicationName",
                            Value = "اتوماسیون اداری سامیاران"
                        });
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchivesKoll");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdKoll")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKoll");

                    b.ToTable("ArchivesMoein");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesTafzilli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AttachedFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdKoll")
                        .HasColumnType("int");

                    b.Property<int>("IdMoein")
                        .HasColumnType("int");

                    b.Property<string>("NameTafzilly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemporaryDeletion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKoll");

                    b.HasIndex("IdMoein");

                    b.ToTable("ArchivesTafzilli");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Units", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Unitsmeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameMeasurement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitsMeasurements");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemporaryDeletion")
                        .HasColumnType("bit");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", "Koll")
                        .WithMany("Moeins")
                        .HasForeignKey("IdKoll")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koll");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesTafzilli", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", "Koll")
                        .WithMany("Tafzillis")
                        .HasForeignKey("IdKoll")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", "Moein")
                        .WithMany("Tafzillis")
                        .HasForeignKey("IdMoein")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koll");

                    b.Navigation("Moein");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", b =>
                {
                    b.Navigation("Moeins");

                    b.Navigation("Tafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", b =>
                {
                    b.Navigation("Tafzillis");
                });
#pragma warning restore 612, 618
        }
    }
}
