// <auto-generated />
using System;
using AutomationEdariSamyaran.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomationEdariSamyaran.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "BackupPath",
                            Value = "C:\\Backup"
                        },
                        new
                        {
                            Id = 2,
                            Key = "ApplicationName",
                            Value = "اتوماسیون اداری سامیاران"
                        });
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchivesKolls");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdKoll")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKoll");

                    b.ToTable("ArchivesMoeins");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesTafzilli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AttachedFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdKoll")
                        .HasColumnType("int");

                    b.Property<int>("IdMoein")
                        .HasColumnType("int");

                    b.Property<string>("NameTafzilly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemporaryDeletion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKoll");

                    b.HasIndex("IdMoein");

                    b.ToTable("ArchivesTafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.CellarKoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CellarKolls");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.CellarMoein", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdKoll")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKoll");

                    b.ToTable("CellarMoeins");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.CellarTafzilli", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdKoll")
                        .HasColumnType("int");

                    b.Property<int>("IdMoein")
                        .HasColumnType("int");

                    b.Property<int>("IdUnitsMeasurement")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKoll");

                    b.HasIndex("IdMoein");

                    b.HasIndex("IdUnitsMeasurement");

                    b.ToTable("CellarTafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_State")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_State");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.DailyReminderTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Displayed")
                        .HasColumnType("bit");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ReminderHour")
                        .HasColumnType("time");

                    b.Property<DateTime>("Reminderdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remindertext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPersonal");

                    b.ToTable("DailyReminderTasks");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Greatadvice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Advice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Greatadvices");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.LetterRecepiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RecepiantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LetterRecepiants");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Letters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AttachedFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateOfView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLetterSubject")
                        .HasColumnType("int");

                    b.Property<int>("IdReceiveLetters")
                        .HasColumnType("int");

                    b.Property<int>("IdSendLetter")
                        .HasColumnType("int");

                    b.Property<string>("LetterNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LetterType")
                        .HasColumnType("int");

                    b.Property<bool>("TemporaryDeletion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdReceiveLetters");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.OrganizationalRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrganRank")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationalRanks");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldofStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FristName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int>("IdDegreeEducation")
                        .HasColumnType("int");

                    b.Property<int>("IdOrganRanks")
                        .HasColumnType("int");

                    b.Property<int?>("IdState")
                        .HasColumnType("int");

                    b.Property<int>("IdUnit")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NationalCode")
                        .HasColumnType("float");

                    b.Property<int>("NumShenasname")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationalRankId")
                        .HasColumnType("int");

                    b.Property<bool>("PersenelActive")
                        .HasColumnType("bit");

                    b.Property<int>("PersonalCode")
                        .HasColumnType("int");

                    b.Property<int>("Postalcode")
                        .HasColumnType("int");

                    b.Property<string>("StartJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemporaryDeletion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdOrganRanks");

                    b.HasIndex("IdState");

                    b.HasIndex("IdUnit");

                    b.HasIndex("OrganizationalRankId");

                    b.ToTable("Personals");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.PhoneBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressWorkplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Homephone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Homephone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localphone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localphone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workphone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workphone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkplaceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPersonal");

                    b.ToTable("PhoneBooks");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Seller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AdressSeller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileSeller")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("NameSeller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TellSeller")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Units", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Unitsmeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameMeasurement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitsMeasurements");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemporaryDeletion")
                        .HasColumnType("bit");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.UserPermission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Archives")
                        .HasColumnType("bit");

                    b.Property<bool>("BackupRestore")
                        .HasColumnType("bit");

                    b.Property<bool>("BackupRoot")
                        .HasColumnType("bit");

                    b.Property<bool>("CompanyInfo")
                        .HasColumnType("bit");

                    b.Property<bool>("Goods")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodsCircReport")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodsDeparture")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodsImpReport")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodsImportation")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodsRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("GoodsRequests")
                        .HasColumnType("bit");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int");

                    b.Property<bool>("KolGoods")
                        .HasColumnType("bit");

                    b.Property<bool>("KollArchives")
                        .HasColumnType("bit");

                    b.Property<bool>("MoeinArchives")
                        .HasColumnType("bit");

                    b.Property<bool>("MoeinGoods")
                        .HasColumnType("bit");

                    b.Property<bool>("OrganizationalChart")
                        .HasColumnType("bit");

                    b.Property<bool>("OrganizationalRank")
                        .HasColumnType("bit");

                    b.Property<bool>("PersonalReport")
                        .HasColumnType("bit");

                    b.Property<bool>("Personallist")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductRequestMessage")
                        .HasColumnType("bit");

                    b.Property<bool>("Publicmessages")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestConfirmation")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestLeave")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestLeavemanagement")
                        .HasColumnType("bit");

                    b.Property<bool>("RequestList")
                        .HasColumnType("bit");

                    b.Property<bool>("Seller")
                        .HasColumnType("bit");

                    b.Property<bool>("UnitsInformation")
                        .HasColumnType("bit");

                    b.Property<bool>("UnitsMeasurement")
                        .HasColumnType("bit");

                    b.Property<bool>("UserSettings")
                        .HasColumnType("bit");

                    b.Property<bool>("letterSendList")
                        .HasColumnType("bit");

                    b.Property<bool>("letterSubject")
                        .HasColumnType("bit");

                    b.Property<bool>("lettersDraft")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("IdPersonal");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.YourNamespace.OrganizationalChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasAFather")
                        .HasColumnType("bit");

                    b.Property<int?>("IdFather")
                        .HasColumnType("int");

                    b.Property<int>("IdOrgan_Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFather");

                    b.HasIndex("IdOrgan_Rank");

                    b.ToTable("OrganizationalCharts");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.letterDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AttachedFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lettersTittel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Draftletters");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.letterSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LetterSubjects");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", "Koll")
                        .WithMany("Moeins")
                        .HasForeignKey("IdKoll")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koll");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesTafzilli", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", "Koll")
                        .WithMany("Tafzillis")
                        .HasForeignKey("IdKoll")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", "Moein")
                        .WithMany("Tafzillis")
                        .HasForeignKey("IdMoein")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koll");

                    b.Navigation("Moein");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.CellarMoein", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.CellarKoll", "Koll")
                        .WithMany("Moeins")
                        .HasForeignKey("IdKoll")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koll");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.CellarTafzilli", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.CellarKoll", "Koll")
                        .WithMany("Tafzillis")
                        .HasForeignKey("IdKoll")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.CellarMoein", "Moein")
                        .WithMany("Tafzillis")
                        .HasForeignKey("IdMoein")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.Unitsmeasurement", "UnitsMeasurement")
                        .WithMany("Tafzillis")
                        .HasForeignKey("IdUnitsMeasurement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koll");

                    b.Navigation("Moein");

                    b.Navigation("UnitsMeasurement");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.City", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("Id_State")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.DailyReminderTask", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.Personal", "Personal")
                        .WithMany("DailyReminders")
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Letters", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.LetterRecepiant", "Recepiant")
                        .WithMany("Letters")
                        .HasForeignKey("IdReceiveLetters")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recepiant");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Personal", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.OrganizationalRank", "organizationalRank")
                        .WithMany()
                        .HasForeignKey("IdOrganRanks")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("IdState")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.Units", "Units")
                        .WithMany()
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.OrganizationalRank", null)
                        .WithMany("Personals")
                        .HasForeignKey("OrganizationalRankId");

                    b.Navigation("City");

                    b.Navigation("State");

                    b.Navigation("Units");

                    b.Navigation("organizationalRank");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.PhoneBook", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.Personal", "Personal")
                        .WithMany("PhoneBooks")
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.Personal", "Personal")
                        .WithMany("UserPermissions")
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.YourNamespace.OrganizationalChart", b =>
                {
                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.YourNamespace.OrganizationalChart", "Father")
                        .WithMany("Children")
                        .HasForeignKey("IdFather")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomationEdariSamyaran.Domain.Entities.OrganizationalRank", "Rank")
                        .WithMany("Charts")
                        .HasForeignKey("IdOrgan_Rank")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Father");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesKoll", b =>
                {
                    b.Navigation("Moeins");

                    b.Navigation("Tafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.ArchivesMoein", b =>
                {
                    b.Navigation("Tafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.CellarKoll", b =>
                {
                    b.Navigation("Moeins");

                    b.Navigation("Tafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.CellarMoein", b =>
                {
                    b.Navigation("Tafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.LetterRecepiant", b =>
                {
                    b.Navigation("Letters");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.OrganizationalRank", b =>
                {
                    b.Navigation("Charts");

                    b.Navigation("Personals");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Personal", b =>
                {
                    b.Navigation("DailyReminders");

                    b.Navigation("PhoneBooks");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.Unitsmeasurement", b =>
                {
                    b.Navigation("Tafzillis");
                });

            modelBuilder.Entity("AutomationEdariSamyaran.Domain.Entities.YourNamespace.OrganizationalChart", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
